import AppKit

/// Pure decision logic: should a pasteboard change be captured, and as what?
/// No NSPasteboard access in here — fully unit-tested in PasteboardCaptureTests.
enum CaptureClassifier {
    /// Type strings whose presence means "never capture". First three are the
    /// nspasteboard.org conventions (password managers, transient content);
    /// the last is Fuse's own marker — skipping it prevents an infinite capture
    /// loop when PasteService writes or restores the clipboard.
    static let forbiddenTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        PasteService.fuseInternalMarker.rawValue,   // "com.rgv250cc.fuse.internal"
    ]

    /// Types present on the pasteboard -> should we capture at all?
    static func shouldCapture(types: Set<String>) -> Bool {
        guard !types.isEmpty else { return false }
        return types.isDisjoint(with: forbiddenTypes)
    }

    /// Map available types + plain string to (kind, preview).
    /// Priority: file > image > rtf > link > text.
    static func classify(types: Set<String>, plainString: String?, fileURLs: [URL],
                         imagePixelSize: CGSize?) -> (kind: String, preview: String) {
        if !fileURLs.isEmpty {
            let names = fileURLs.map(\.lastPathComponent).joined(separator: ", ")
            return ("file", String(names.prefix(200)))
        }
        if types.contains("public.png") || types.contains("public.tiff") {
            if let size = imagePixelSize {
                return ("image", "Image \(Int(size.width))x\(Int(size.height))")
            }
            return ("image", "Image")
        }
        if types.contains("public.rtf") {
            return ("rtf", String((plainString ?? "RTF text").prefix(200)))
        }
        if let plainString {
            let trimmed = plainString.trimmingCharacters(in: .whitespacesAndNewlines)
            if isLink(trimmed) { return ("link", String(trimmed.prefix(200))) }
            return ("text", String(plainString.prefix(200)))
        }
        return ("other", types.sorted().first ?? "unknown")
    }

    /// A "link" is a single token that parses as an http/https URL with a host.
    private static func isLink(_ s: String) -> Bool {
        guard !s.isEmpty,
              s.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
              let url = URL(string: s),
              let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https",
              url.host != nil
        else { return false }
        return true
    }
}
