import AppKit
import XCTest
@testable import Fuse

final class PasteboardCaptureTests: XCTestCase {
    private func classify(_ types: Set<String>, _ s: String? = nil,
                          files: [URL] = [], px: CGSize? = nil) -> (kind: String, preview: String) {
        CaptureClassifier.classify(types: types, plainString: s, fileURLs: files, imagePixelSize: px)
    }

    func testShouldCaptureRejectsForbiddenAndEmptyTypes() {
        XCTAssertTrue(CaptureClassifier.shouldCapture(types: ["public.utf8-plain-text", "public.html"]))
        XCTAssertFalse(CaptureClassifier.shouldCapture(types: []))
        let forbidden = ["org.nspasteboard.ConcealedType",      // password managers
                         "org.nspasteboard.TransientType",
                         "org.nspasteboard.AutoGeneratedType",
                         PasteService.fuseInternalMarker.rawValue]  // Fuse's own writes — loop guard
        for bad in forbidden {
            XCTAssertFalse(CaptureClassifier.shouldCapture(types: ["public.utf8-plain-text", bad]), bad)
        }
    }

    func testClassifyFileBeatsEverythingAndJoinsNames() {
        let one = classify(["public.file-url", "public.png", "public.utf8-plain-text"], "/tmp/a.png",
                           files: [URL(fileURLWithPath: "/tmp/a.png")], px: CGSize(width: 9, height: 9))
        XCTAssertEqual(one.kind, "file")
        XCTAssertEqual(one.preview, "a.png")
        let two = classify(["public.file-url"],
                           files: [URL(fileURLWithPath: "/tmp/a.txt"), URL(fileURLWithPath: "/tmp/b.txt")])
        XCTAssertEqual(two.preview, "a.txt, b.txt")
    }

    func testClassifyImageWithAndWithoutPixelSize() {
        let sized = classify(["public.png", "public.tiff"], px: CGSize(width: 800, height: 600))
        XCTAssertEqual(sized.kind, "image")
        XCTAssertEqual(sized.preview, "Image 800x600")
        let unsized = classify(["public.tiff"])
        XCTAssertEqual(unsized.kind, "image")
        XCTAssertEqual(unsized.preview, "Image")
    }

    func testClassifyRTFUsesPlainStringPreview() {
        let result = classify(["public.rtf", "public.utf8-plain-text"], "styled words")
        XCTAssertEqual(result.kind, "rtf")
        XCTAssertEqual(result.preview, "styled words")
    }

    func testClassifyLinkRequiresHttpSchemeAndHost() {
        let https = classify(["public.utf8-plain-text"], "https://example.com/page?x=1")
        XCTAssertEqual(https.kind, "link")
        XCTAssertEqual(https.preview, "https://example.com/page?x=1")
        let padded = classify(["public.utf8-plain-text"], "  http://example.com\n")
        XCTAssertEqual(padded.kind, "link")
        XCTAssertEqual(padded.preview, "http://example.com")   // preview is the trimmed URL
    }

    func testClassifyNonLinksFallBackToText() {
        XCTAssertEqual(classify(["public.utf8-plain-text"], "ftp://example.com/file").kind, "text")
        XCTAssertEqual(classify(["public.utf8-plain-text"], "see https://example.com for details").kind, "text")
        XCTAssertEqual(classify(["public.utf8-plain-text"], "plain words").kind, "text")
    }

    func testClassifyTextTruncatesPreviewTo200Chars() {
        let result = classify(["public.utf8-plain-text"], String(repeating: "x", count: 500))
        XCTAssertEqual(result.kind, "text")
        XCTAssertEqual(result.preview.count, 200)
    }

    func testClassifyUnknownTypesFallBackToOther() {
        let result = classify(["com.example.custom"])
        XCTAssertEqual(result.kind, "other")
        XCTAssertEqual(result.preview, "com.example.custom")
    }
}
